# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the local Python script into the container
COPY main.py .

# Define the command to run when the container starts
CMD ["python", "main.py"]
